---
# NOTICE: Even when 'when'-conditions are False, expressions are evaluated by Ansible and throw errors like "NoneType is not iterable"...
- name: Reset Ceph config parameter to empty list when null
  ansible.builtin.set_fact:
    pve_ceph_config: "{{ [] }}"
  when: "pve_ceph_config is none"

- name: Apply custom Ceph configuration
  vars:
    space: " "
    comma: ","
    default_scope: "client"
    valid_scopes: "{{ ['global', 'client', 'osd', 'mon', 'mgr', 'mds'] }}"
    ignore_invalid: false
  when:
    - "inventory_hostname == _ceph_init_node"
    - "pve_ceph_config | length > 0"
  block:
    - name: Collect valid Ceph values
      block:
        - name: Query valid Ceph config list
          ansible.builtin.command: "ceph config ls --format json"
          register: _ceph_config_ls_raw
          changed_when: false

        - name: Normalize valid Ceph config list
          ansible.builtin.set_fact:
            _ceph_config_ls: "{{ _ceph_config_ls_raw.stdout | from_json }}"

    - name: Normalize Ceph config variable
      block:
        - name: Normalize Ceph config values from dict into list structure
          block:
            - name: Create temporary config variable
              ansible.builtin.set_fact:
                _tmp_ceph_config: "{{ [] }}"
              when: "pve_ceph_config is mapping"

            - name: Normalize Ceph config dict variable structure
              ansible.builtin.set_fact:
                # Normalize from [<who>:{<key>: <value>}] into [<who>,{'key': ..., 'value': ...}] form.
                _tmp_ceph_config: "{{ _tmp_ceph_config + [item.key] | product(item.value | dict2items) }}"
              loop: "{{ pve_ceph_config is mapping | ternary(pve_ceph_config, {}) | dict2items }}"
              when: "_tmp_ceph_config is defined"

#            - debug:
#                msg: "_tmp_ceph_config: {{ _tmp_ceph_config | default('UNDEF') }}"

            - name: Apply first normalization
              ansible.builtin.set_fact:
                pve_ceph_config: "{{ _tmp_ceph_config }}"
                _tmp_ceph_config: "{{ [] }}"
              when: "_tmp_ceph_config is defined"

            - name: Normalize Ceph config list variable structure
              ansible.builtin.set_fact:
                # Normalize from [<who>,{<key>: <value>}] into [{'who':..., 'name': ..., 'value': ...}] form.
                _tmp_ceph_config: "{{ _tmp_ceph_config + [{'who': item[0], 'name': item[1].key, 'value': item[1].value}] }}"
              loop: "{{ pve_ceph_config | default([], true) | list }}"
              when: "_tmp_ceph_config is defined"

            - name: Apply second normalization
              ansible.builtin.set_fact:
                pve_ceph_config: "{{ _tmp_ceph_config }}"
                _tmp_ceph_config: "{{ [] }}"
              when: "_tmp_ceph_config is defined"

#            - debug:
#                msg: "pve_ceph_config: {{ pve_ceph_config }}"

        - name: Normalize Ceph config values into list of named configs
          ansible.builtin.set_fact:
            # Normalize from [{<key>: <value>}] into [{'name': ..., 'value': ...}] form.
            pve_ceph_config: "{{ pve_ceph_config | selectattr('name', 'defined') + (pve_ceph_config | rejectattr('name', 'defined')
              | map('dict2items', key_name='name') | flatten) }}"
          when: "pve_ceph_config | rejectattr('name', 'defined') | length > 0"

        - name: Initialize Ceph config values 'who' attribute
          ansible.builtin.set_fact:
            # If 'who' undefined or defined but == none -> replace with default_scope
            pve_ceph_config: "{{ pve_ceph_config | selectattr('who', 'defined') | selectattr('who', '!=', none) + pve_ceph_config
              | selectattr('who', 'defined') | selectattr('who', '==', none) | map('combine', {'who': default_scope}) + pve_ceph_config
              | selectattr('who', 'undefined') | map('combine', {'who': default_scope}) }}"
          when: "pve_ceph_config | selectattr('who', 'defined') | selectattr('who', '==', none) | length > 0 or pve_ceph_config
            | selectattr('who', 'undefined') | length > 0"

        - name: Normalize Ceph config by indexing and removing duplicates
          block:
            - name: Create temporary loop variable copy
              ansible.builtin.set_fact:
                _tmp_loop: "{{ pve_ceph_config | list }}"

            - name: Index ceph configs, Remove duplicates
              ansible.builtin.set_fact:
                # Take care of same name but different 'who' scope which is legit. This is 'filter by name AND who attribute'.
                pve_ceph_config: "{{ pve_ceph_config | rejectattr('name', '==', item.name) + pve_ceph_config | selectattr('name',
                  '==', item.name) | rejectattr('who', '==', item.who) + [item | combine({'id': idx})] }}"
              loop: "{{ _tmp_loop }}"
              loop_control:
                index_var: idx

        - name: Remove invalid values if requested
          when: "ignore_invalid | bool"
          block:
            - name: Create temporary loop variable copy
              ansible.builtin.set_fact:
                _tmp_loop: "{{ pve_ceph_config | list }}"

            - name: Remove invalid Ceph config values
              ansible.builtin.set_fact:
                pve_ceph_config: "{{ pve_ceph_config | rejectattr('name', '==', item.name) }}"
              loop: "{{ _tmp_loop }}"
              when: "item.name not in _ceph_config_ls"

        - name: Display normalized Ceph config parameter
          ansible.builtin.debug:
            msg: "pve_ceph_config: {{ pve_ceph_config | default('UNDEF') }}"

    - name: Validate Ceph config values
      block:
        - name: Ensure correct Ceph config names
          ansible.builtin.assert:
            that: "item.name in _ceph_config_ls"
            msg: "Ceph config 'name' of {{ item }} is invalid!"
          loop: "{{ pve_ceph_config | default([], true) }}"

        - name: Ensure correct 'who' scope for Ceph config
          ansible.builtin.assert:
            that: "item.who in valid_scopes"
            msg: "'who' scope of Ceph config variable {{ item }} is invalid!"
          loop: "{{ pve_ceph_config | default([], true) }}"

    - name: Collect Ceph config default values
      block:
        - name: Query config defaults for config keys
          ansible.builtin.command: "ceph config help {{ item.name }} --format json"
          register: _ceph_config_help_raws
          loop: "{{ pve_ceph_config | default([], true) }}"
          changed_when: false

        - name: Extract config values metadata
          ansible.builtin.set_fact:
            _ceph_config_defaults: "{{ _ceph_config_defaults | default([]) + [item.stdout | from_json | combine({'separator':
              none})] }}"
          loop: "{{ _ceph_config_help_raws.results | default([]) }}"
          loop_control:
            label: "{{ item.item }}"

        - name: Create temporary loop variable copy
          ansible.builtin.set_fact:
            _tmp_loop: "{{ _ceph_config_defaults | list }}"

        - name: Normalize comma separated string list config default values
          ansible.builtin.set_fact:
            _ceph_config_defaults: "{{ _ceph_config_defaults | rejectattr('name', '==', item.name) + [item | combine({'default':
              item.default | split(comma) | map('trim'), 'separator': comma, 'type': 'list'})] }}"
          loop: "{{ _tmp_loop }}"
          when:
            - "item.default is string"
            - "comma in (item.default | list)"

        - name: Normalize space separated string list config default values
          ansible.builtin.set_fact:
            _ceph_config_defaults: "{{ _ceph_config_defaults | rejectattr('name', '==', item.name) + [item | combine({'default':
              item.default | trim | split(space), 'separator': space, 'type': 'list'})] }}"
          loop: "{{ _tmp_loop }}"
          when:
            - "item.default is string"
            - "space in (item.default | trim | list)"

        - name: Display found Ceph config default values
          ansible.builtin.debug:
            msg: "_ceph_config_defaults: {{ _ceph_config_defaults | default('UNDEF') }}"

    - name: Calculate requested Ceph config values
      block:
        - name: Create config variable
          ansible.builtin.set_fact:
            _ceph_configs: "{{ [] }}"

        - name: Collect non-list absolute config values
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs + [item | combine({'separator': list_sep})] }}"
          vars:
            default_item: "{{ (_ceph_config_defaults | selectattr('name', '==', item.name) | first) }}"
            list_sep: "{{ item.separator | default(default_item.separator, true) }}"
          loop: "{{ pve_ceph_config | default([], true) }}"
          when: # Filter out all strings that start with + or - (relative values) or contain space or comma (are string lists).
            - "item.value is not iterable or item.value is string"
            - "item.value is not string or not (item.value.startswith('+') or item.value.startswith('-') or [comma,  space]
              | intersect(item.value | trim | list) | length > 0)" # => item.value contains comma or space

        - name: Collect and separate non-list relative string config values
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs + [item | combine(updated_item)] }}"
          vars:
            addition: "{{ item.value is match('^\\+') | ternary([item.value | regex_replace('^\\+', '')], []) }}"
            subtraction: "{{ item.value is match('^-') | ternary([item.value | regex_replace('^-', '')], []) }}"
            default_item: "{{ (_ceph_config_defaults | selectattr('name', '==', item.name) | first) }}"
            list_sep: "{{ item.separator | default(default_item.separator, true) }}"
            updated_item: "{{ {'value': none, 'add': addition, 'rem': subtraction, 'separator': list_sep} }}"
          loop: "{{ pve_ceph_config | default([], true) }}"
          when:
            - "item.value is string"
            - "item.value.startswith('+') or item.value.startswith('-')"
            - "[comma, space] | intersect(item.value | trim | list) | length == 0" # => item.value not contains comma or space

        - name: Collect and normalize comma separated string list config values into lists
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs + [item | combine({'value': item.value | split(comma) | map('trim'), 'separator':
              comma})] }}"
          loop: "{{ pve_ceph_config | default([], true) }}"
          when:
            - "item.value is string"
            - "comma in (item.value | list)"

        - name: Collect and normalize space separated string list config values into lists
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs + [item | combine({'value': item.value | trim | split(space), 'separator': space})]
              }}"
          loop: "{{ pve_ceph_config | default([], true) }}"
          when:
            - "item.value is string"
            - "space in (item.value | trim | list)"

        - name: Create temporary loop variable copy
          ansible.builtin.set_fact:
            _tmp_loop: "{{ _ceph_configs | list }}"

        - name: Collect and separate absolute and relative list config values
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': absolute_values,
              'add': additions, 'rem': subtractions})] }}"
          vars:
            absolute_values: "{{ item.value | reject('string') + (item.value | select('string') | reject('match', '^-') |
              reject('match', '^\\+')) | default(none, true) }}"
            additions: "{{ item.value | select('string') | select('match', '^\\+') | map('regex_replace', '^\\+', '') }}"
            subtractions: "{{ item.value | select('string') | select('match', '^-') | map('regex_replace', '^-', '') }}"
          loop: "{{ _tmp_loop }}"
          when:
            - "item.value is iterable"
            - "item.value is not string"
            - "item.value | length > 0"

        - name: Create temporary loop variable copy
          ansible.builtin.set_fact:
            _tmp_loop: "{{ _ceph_configs | list }}"

        - name: Reset value to default if no absolute value is defined
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': default_item.default})]
              }}"
          vars:
            default_item: "{{ (_ceph_config_defaults | selectattr('name', '==', item.name) | first) }}"
          loop: "{{ _tmp_loop }}"
          when: "item.value is not defined or item.value is none"

        - name: Create temporary loop variable copy
          ansible.builtin.set_fact:
            _tmp_loop: "{{ _ceph_configs | list }}"

        - name: Add relative Ceph config value declarations
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': (item.value | default([],
              true) + item.add) | unique})] }}"
          loop: "{{ _tmp_loop }}"
          when: "item.add | default([]) | length > 0"

        - name: Create temporary loop variable copy
          ansible.builtin.set_fact:
            _tmp_loop: "{{ _ceph_configs | list }}"

        - name: Remove relative Ceph config value declarations
          ansible.builtin.set_fact:
            _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': item.value | default([],
              true) | difference(item.rem)})] }}"
          loop: "{{ _tmp_loop }}"
          when: "item.rem | default([]) | length > 0"

    - name: Prepare iterable Ceph config values
      ansible.builtin.set_fact:
        _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': item.value | join(item.separator)})]
          }}"
      loop: "{{ _ceph_configs }}"
      when:
        - "item.value is iterable"
        - "item.value is not string"
        - "item.separator | default(false, true) is not false"

    - name: Prepare string Ceph config values
      ansible.builtin.set_fact:
        _ceph_configs: "{{ _ceph_configs | rejectattr('id', '==', item.id) + [item | combine({'value': '\"\"'})] }}"
      loop: "{{ _ceph_configs }}"
      when:
        - "item.value is string"
        - "item.value | length == 0"

    - name: Display finished Ceph config
      ansible.builtin.debug:
        msg: "_ceph_configs: {{ _ceph_configs | default('UNDEF') }}"

    - name: Apply Ceph config values
      ansible.builtin.command: "ceph config set {{ item.who }} {{ item.name }} {{ item.value }}"
      loop: "{{ _ceph_configs }}"
      changed_when: true
