---

- name: Prepare ceph update
  block:
    - name: Ensure Ceph health is OK before proceeding
      ansible.builtin.import_tasks: common/check_ceph_health.yml

    - name: Validate datacenter.cfg migration strategy
      ansible.builtin.import_tasks: prepare/check_migration_strategy.yml

    - name: Set the noout flag for the OSDs
      ansible.builtin.import_tasks: common/set_noout_flag.yml

    - name: Run OS-Upgrades
      ansible.builtin.import_tasks: prepare/apt_upgrades.yml

    - name: Unset the noout flag for the OSDs
      ansible.builtin.import_tasks: common/unset_noout_flag.yml
    
    - name: Validate if all updates are done 
      ansible.builtin.import_tasks: prepare/validate_apt_upgrades.yml

    - name: Ensure Ceph health is OK before proceeding
      ansible.builtin.import_tasks: common/check_ceph_health.yml

    # check for syntax
    - name: Disable Ceph telemetry
      ansible.builtin.import_tasks: prepare/disable_ceph_telemetry.yml

- name: Conduct upgrade
  block:

    - name: Update APT cache on all nodes and do the distro upgrade, without reboot
      ansible.builtin.import_tasks: upgrade/ceph_apt_upgrades.yml

    - name: Restart ceph-mon sequentially (with health check between)
      ansible.builtin.import_tasks: upgrade/restart_ceph_mons.yml

    - name: Check if Ceph is healthy after restarting monitors
      ansible.builtin.import_tasks: common/check_ceph_health.yml

    - name: Check if ceph-mons were updated to the new version
      ansible.builtin.import_tasks: upgrade/validate_ceph_mon_status.yml

    - name: Restart ceph-mgr services (only if running)
      ansible.builtin.import_tasks: upgrade/restart_ceph_mgr.yml

    - name: Check if ceph-mgrs were updated to the new version
      ansible.builtin.import_tasks: upgrade/validate_ceph_mgr_status.yml

    - name: Ensure Ceph health is OK after restarts
      ansible.builtin.import_tasks: common/check_ceph_health.yml

    - name: Set the noout flag during restarting the OSDs
      ansible.builtin.import_tasks: common/set_noout_flag.yml

    - name: Restart the OSDs
      ansible.builtin.import_tasks: upgrade/restart_ceph_osds.yml
    
    - name: Unset the noout flag during restarting the OSDs
      ansible.builtin.import_tasks: common/unset_noout_flag.yml
    
    - name: Set Ceph to required minimum OSD release
      ansible.builtin.import_tasks: upgrade/require_osd_release.yml

    - name: Ensure Ceph health is OK after restarts
      ansible.builtin.import_tasks: common/check_ceph_health.yml

    - name: Upgrade CephFS MDS daemons safely
      ansible.builtin.import_tasks: upgrade/upgrade_cephfs_mds.yml

- name: Clean up 
  block:
   
    - name: Final Ceph health check
      ansible.builtin.import_tasks: common/check_ceph_health.yml
    
    - name: Enable ceph telemetry, if desired
      ansible.builtin.import_tasks: cleanup/reenable_ceph_telemetry.yml

- name: Acknowledge all healt warnings <- should never run unless triggert by calling with specific tag
  tags:
    - never
    - chup_acknowledge_warnings
  block:
     - name: acknowledge warnings
       ansible.builtin.import_tasks: common/acknowledge_health_warns.yml
