# main tasks file for ansible-role-proxmox
# just call other tasks here (with their tags)
---
- name: Gather, normalize, validate, build variables
  ansible.builtin.import_tasks: prepare/load_variables.yml
  tags:
    - always
    - variables

- name: Gather package (un-)installation candidates
  ansible.builtin.import_tasks: prepare/identify_needed_packages.yml
  tags:
    - always
    - prepare

- name: Configure name resolution within the cluster
  ansible.builtin.import_tasks: system/name_resolution.yml
  tags:
    - name_resolution

# TODO enable and config ssh for single nodes when pve_manage_ssh and not pve_cluster_enabled
- name: Configure mutual SSH keys on hosts for cluster joins
  ansible.builtin.import_tasks: system/ssh_config.yml
  when:
    - "pve_manage_ssh | bool"
    - "pve_cluster_enabled | bool"
  tags:
    - ssh

- name: Upgrade or downgrade the system packages
  ansible.builtin.import_tasks: system/apt.yml
  tags:
    - apt

- name: Set and apply sysctl configuration
  ansible.builtin.import_tasks: system/sysctl.yml
  tags:
    - sysctl

# needs testing
- ansible.builtin.import_tasks: system/pcie_passthrough.yml
  when: "pve_pcie_passthrough_enabled | bool"
  tags:
    - pcie

- name: Update kernels, possibly reboot hosts
  ansible.builtin.import_tasks: system/kernel_updates.yml
  tags:
    - kernel

# needs analysis later
- ansible.builtin.import_tasks: system/ipmi_watchdog.yml
  when: "pve_watchdog == 'ipmi'"
  tags:
    - watchdog

## TODO (remove) Needs analysis later, is obsolete when modules are handled during their tasks, 
#  to enable standalone aka tagged execution
#- ansible.builtin.import_tasks: kernel_module_cleanup.yml
#  when: false

- name: Validate PVE clustering and standalone settings (needs to be done after pve installation)
  ansible.builtin.import_tasks: prepare/validate_runtime_settings.yml
  tags:
    - always
    - validate_runtime_settings

- name: Manage PVE cluster settings
  ansible.builtin.import_tasks: cluster/pve_cluster.yml
  when: "pve_cluster_enabled | bool"
  tags:
    - cluster

- name: Manage PVE cluster HA groups
  ansible.builtin.import_tasks: cluster/ha_groups.yml
  when: "pve_cluster_enabled | bool"
  tags:
    - ha_groups

- name: Manage PVE cluster HA guests
  ansible.builtin.import_tasks: cluster/ha_manager.yml
  when: "pve_cluster_enabled | bool"
  tags:
    - ha_manager

- name: Configuration of PVE storage pools
  tags: storage
  block:
    - ansible.builtin.import_tasks: storage/ceph/legacy/ceph.yml
      when:
        - "pve_ceph_enabled | bool"
        - "pve_cluster_enabled | bool"
        - "inventory_hostname in pve_ceph_nodes or inventory_hostname_short in pve_ceph_nodes"
      tags:
        - ceph

    - ansible.builtin.import_tasks: storage/ceph/ceph_cluster.yml
      when:
        - "pve_ceph_enhanced_enabled | bool"
        - "pve_cluster_enabled | bool"
        - "inventory_hostname in pve_ceph_nodes or inventory_hostname_short in pve_ceph_nodes"
      tags:
        - ceph

    - name: Setup ZFS storage pools
      ansible.builtin.import_tasks: storage/zfs/setup.yml
      when: "pve_zfs_enabled | bool"
      tags:
        - zfs

    - name: Configuration of ZFS storage pools
      ansible.builtin.import_tasks: storage/zfs/pool_conf.yml
      when: "pve_zfs_enabled | bool"
      tags:
        - zfs

    - name: Setup additional filesystems
      ansible.builtin.import_tasks: storage/filesystems.yml
      tags:
        - filesystems

    # NOTICE: Execute after any other storage tasks
    - name: Manage PVE storage definitions
      ansible.builtin.import_tasks: storage/storage_pve.yml
      tags:
        - storage_pve

- name: Configure Identity and Access
  ansible.builtin.import_tasks: access/access.yml
  tags:
    - access
    - iam

- name: Manage PVE datacenter settings
  ansible.builtin.import_tasks: cluster/datacenter_options.yml
  tags:
    - datacenter_cfg
    - datacenter_options

- name: Configure metric export to monitoring server
  ansible.builtin.import_tasks: cluster/metric_server.yml
  tags:
    - metrics

- name: Manage pveproxy settings
  ansible.builtin.import_tasks: system/proxy+ssl_config.yml
  tags:
    - ssl
    - pve_proxy
