---
# TODO validation via "pvesh get /cluster/options"

- name: Manage PVE datacenter options
  when: "inventory_hostname == _init_node"
  block:
    - name: Touch the datacenter.cfg files if they haven't exists in advanced (due to behaviour of pmxcfs)
      ansible.builtin.file:
        path: "/etc/pve/datacenter.cfg"
        state: touch
        mode: "644"
      when: "pve_datacenter_options | length > 0"

    - name: Set datacenter options file for custom datacenter options
      ansible.builtin.template:
        src: "templates/cluster/datacenter.cfg.j2"
        dest: "/etc/pve/datacenter.cfg"
        owner: "root"
        group: "www-data"
        mode: "0640"
      when: "pve_datacenter_options | length > 0"

    - name: Remove datacenter.cfg file if no values are defined
      ansible.builtin.file:
        path: "/etc/pve/datacenter.cfg"
        state: absent
      when: "pve_datacenter_options | length == 0"
