---
- name: Check if ceph-mgr service exists on this node
  ansible.builtin.command:
    cmd: "systemctl list-units --all --type=service --output=json" # noqa: command-instead-of-module
  register: _systemd_services_raw

- name: Extract ceph-mgr services
  ansible.builtin.set_fact:
    _systemd_ceph_mgr_services: "{{ _systemd_services_raw.stdout | from_json | json_query(jquery) }}"
  vars:
    jquery: "[?unit.contains(@,'ceph-mgr')].unit"

- name: Display found ceph-manager services per host
  ansible.builtin.debug:
    var: _systemd_ceph_mgr_services

- name: Reset restart timer for ceph-mgr.service, avoiding conflicts of previous failed restart attempts
  ansible.builtin.command:
    cmd: "systemctl reset-failed {{ item }}" # noqa: command-instead-of-module
  loop: "{{ _systemd_ceph_mgr_services }}"

- name: Restart ceph-mgr.service one by one
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  register: _systemd_ceph_mgr_service_restart
  failed_when: "_systemd_ceph_mgr_service_restart.rc != 0"
  retries: 4
  delay: 20
  throttle: 1
  loop: "{{ _systemd_ceph_mgr_services }}"
