---
# Must be run before any other apt task or else apt task will fail on missing auth
- name: Remove automatically created VE Enterprise repo configuration
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    state: absent

- name: Trust Proxmox' packaging key on Debian < 12
  ansible.builtin.apt_key:
    data: "{{ lookup('file', pve_release_key) }}"
    id: "{{ pve_release_key_id }}"
    state: present
  when: "ansible_distribution_major_version | int < 12"

- name: Trust Proxmox' packaging key on Debian >= 12
  ansible.builtin.copy:
    src: "proxmox-release-{{ ansible_distribution_release }}.gpg"
    dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg"
    mode: "0644"
  when: "ansible_distribution_major_version | int >= 12"

- name: Setup Proxmox repositories
  ansible.builtin.import_tasks: repositories.yml

- name: Manage PVE-Kernel version pinning
  block:
    - name: Add PVE-Kernel pinning if defined
      ansible.builtin.template:
        src: "system/apt/pve-kernel-pin.j2"
        dest: "/etc/apt/preferences.d/proxmox-kernel-pin"
        mode: "0644"
      when: "pve_pin_kernel_version | default(false, true) is not false"

    - name: Remove PVE-Kernel pinning if not defined
      ansible.builtin.file:
        path: "/etc/apt/preferences.d/proxmox-kernel-pin"
        state: absent
      when: "pve_pin_kernel_version | default(false, true) is false"

- name: Ensure required packages for this role are installed
  ansible.builtin.apt:
    name:
      - gpg # needed for trusting keys in apt
      - python3-apt # required by Ansible
      - openssl # needed by ssl_config tasks
      - openvswitch-switch # needed for ovs-configuration
      - jq # needed to parse json-output of commands
    state: present
    update_cache: true

- name: Remove disturbing packages before PVE install
  ansible.builtin.apt:
    name:
      - os-prober
      - linux-image-amd64
    state: absent

- name: Silence grub-pc device selection prompt
  ansible.builtin.debconf:
    name: grub-pc
    question: grub-pc/install_devices_empty
    value: "true"
    vtype: boolean
  when: "ansible_distribution_major_version | int >= 12"

- name: Perform safe upgrades on repo changes
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: "safe"
    allow_downgrade: true
  until: "_system_upgrade is succeeded"
  when:
    "_pve_debian_repo.changed | bool
    or _pve_repo.changed | bool
    or _pve_ceph_repo.changed | bool"
  retries: 3
  register: _system_upgrade

- name: Perform system dist upgrades if requested
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: "dist"
    allow_downgrade: true
  until: "_system_upgrade is succeeded"
  when: "pve_run_system_upgrades | bool"
  retries: 3
  register: _system_upgrade

- name: Setup Proxmox repositories
  ansible.builtin.import_tasks: repositories.yml

- name: Install Proxmox VE and related packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ _pve_install_packages }}"
    state: "{{ 'latest' if pve_run_proxmox_upgrades else 'present' }}"
  until: "_proxmox_install is succeeded"
  retries: 2
  register: _proxmox_install

- name: Remove automatically created VE Enterprise repo source (again) after PVE install
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    state: absent

- name: Remove unnecessary or unwanted apt packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ _pve_uninstall_packages }}"
    state: absent
    autoremove: true
    autoclean: true
    purge: true
  retries: 3
  register: _apt_uninstall
  until: "_apt_uninstall is succeeded"
  when: "_pve_uninstall_packages | default([]) | length > 0"

- name: Remove subscription check wrapper function in web UI
  ansible.builtin.lineinfile:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    line: '        orig_cmd(); return;'
    insertafter: '^\s+checked_command: function\(orig_cmd\) {$'
    firstmatch: true
    backup: true
  when: "pve_remove_subscription_warning | bool"
