---
# Reference: https://pve.proxmox.com/wiki/Package_Repositories
- name: Manage deb822 repositories
  when: "ansible_distribution_major_version | int > 12"
  block:

    - name: Add Debian repository
      ansible.builtin.deb822_repository:
        name: debian
        types:
          - deb
          - deb-src
        uris: https://deb.debian.org/debian
        suites:
          - "{{ pve_debian_version }}"
          - "{{ pve_debian_version }}-updates"
        components:
          - main
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
        state: present
      register: _pve_repositories
      when: pve_manage_debian_repository | bool

    - name: Add Debian security repository
      ansible.builtin.deb822_repository:
        name: debian-security
        types:
          - deb
          - deb-src
        uris: https://security.debian.org/debian-security
        suites: "{{ pve_debian_version }}-security"
        components:
          - main
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
        state: present
      register: _pve_repositories
      when: pve_manage_debian_repository | bool

    - name: Add Proxmox no-subscription repository
      ansible.builtin.deb822_repository:
        name: proxmox
        types: deb
        uris: "{{ pve_repository.uris }}"
        suites: "{{ pve_debian_version }}"
        components: pve-no-subscription
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ pve_debian_version }}.gpg
        state: present
      register: _pve_repositories
      when: not (pve_enable_enterprise_repository | bool)

    # Even when the no-subscription version is uses, the sources for the enterprise version
    # have to be defined in disabled state here. Otherwise this file is generated by a fresh proxmox
    # installation itself and fails with access denied error. Creating this file in disabled state
    # prevents this error-case
    - name: Add Proxmox enterprise repository
      ansible.builtin.deb822_repository:
        name: pve-enterprise
        types: deb
        uris: "{{ pve_repository.uris }}"
        suites: "{{ pve_debian_version }}"
        components: "pve-enterprise"
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ pve_debian_version }}.gpg
        state: present
        enabled: "{{ pve_enable_enterprise_repository | bool }}"
      register: _pve_repositories

    - name: Add Proxmox Ceph repository
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        uris: "{{ pve_ceph_repository.uris }}"
        suites: "{{ pve_debian_version }}"
        components: "{{ pve_ceph_repository.components }}"
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ pve_debian_version }}.gpg
        state: present
      register: _pve_repositories
      when: pve_ceph_enabled | bool or pve_ceph_enhanced_enabled | bool

- name: Manage non-deb822 repositories
  when: "ansible_distribution_major_version | int <= 12"
  block:
    - name: Set debian mirrors in /etc/apt/sources.list
      ansible.builtin.template:
        src: "system/apt/sources.list.j2"
        dest: "/etc/apt/sources.list"
        mode: "0644"
      register: _pve_repositories
      when: "pve_manage_debian_repository | bool"

    - name: Set the Proxmox apt source list file
      ansible.builtin.template:
        src: "system/apt/pve.list.j2"
        dest: "/etc/apt/sources.list.d/pve.list"
        backup: true
        mode: "0644"
        validate: "apt-get update -o Dir::Etc::sourcelist=%s"
      register: _pve_repositories

    - name: Set the Ceph apt source list file
      ansible.builtin.template:
        src: "system/apt/pve_ceph.list.j2"
        dest: "/etc/apt/sources.list.d/ceph.list"
        backup: true
        mode: "0644"
        validate: "apt-get update -o Dir::Etc::sourceParts=%s"
      register: _pve_repositories
      when:
        - (pve_ceph_enabled | bool) or (pve_ceph_enhanced_enabled | bool)

    - name: Ensure PVE enterprise repository is absent
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/pve-enterprise.list"
        state: absent
      register: _pve_repositories
      when: not (pve_enable_enterprise_repository | bool)

- name: Update repositories
  ansible.builtin.apt:
    update_cache: true
  when: _pve_repositories.changed | bool
