---
- name: Stage packages needed for base PVE installation
  ansible.builtin.set_fact:
    _pve_install_packages:
      - proxmox-ve
      - open-iscsi
      - systemd-sysv

- name: Stage any extra packages the user has specified
  ansible.builtin.set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(pve_extra_packages) }}"

- name: Stage packages for uninstallation the user has defined
  ansible.builtin.set_fact:
    _pve_uninstall_packages: "{{ _pve_uninstall_packages | default([]) | union(pve_extra_uninstall_packages) }}"

- name: Stage kernel same memory page merging packages for installation if ksm is enabled
  ansible.builtin.set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(['ksm-control-daemon']) }}"
  when: "pve_ksm_enabled | bool"

- name: Stage kernel same memory page merging packages for uninstallation if ksm is disabled
  ansible.builtin.set_fact:
    _pve_uninstall_packages: "{{ _pve_uninstall_packages | union(['ksm-control-daemon']) }}"
  when: "not pve_ksm_enabled"

- name: Stage ZFS packages for installation if ZFS is enabled
  ansible.builtin.set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(['zfsutils-linux', 'zfs-initramfs', 'zfs-zed']) }}"
  when: "pve_zfs_enabled | bool"

- name: Stage ZFS packages for uninstallation if ZFS is disabled
  ansible.builtin.set_fact:
    _pve_uninstall_packages: "{{ _pve_uninstall_packages | union(['zfsutils-linux', 'zfs-initramfs', 'zfs-zed']) }}"
  when: "not pve_zfs_enabled"

- name: Stage Ceph packages for installation if Ceph is enabled
  ansible.builtin.set_fact:
#    _pve_install_packages: "{{ _pve_install_packages | union(['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse', 'gdisk']) }}"
    _pve_install_packages: "{{ _pve_install_packages | union(['ceph-mon', 'ceph-osd', 'ceph-mgr', 'ceph-mds', 'ceph-base' ,'ceph-mgr-modules-core']) }}"
  when: "(pve_ceph_enabled | bool) or (pve_ceph_enhanced_enabled | bool)"

- name: Stage Ceph packages for uninstallation if Ceph is disabled
  ansible.builtin.set_fact:
#    _pve_uninstall_packages: "{{ _pve_uninstall_packages | union(['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse', 'gdisk']) }}"
    _pve_uninstall_packages: "{{ _pve_uninstall_packages | union(['ceph-mon', 'ceph-osd', 'ceph-mgr', 'ceph-mds', 'ceph-base', 'ceph-mgr-modules-core']) }}"
  when: "not (pve_ceph_enabled | bool or pve_ceph_enhanced_enabled | bool)"
