---
- name: Gather distribution specific variables
  ansible.builtin.include_vars: "debian-{{ ansible_distribution_release }}.yml"

- name: Ensure pve_group variable is valid
  ansible.builtin.assert:
    that:
      - "pve_group | length > 0"
      - "pve_group is string or pve_group is iterable"
      - "[pve_group] | flatten | map('extract', groups) | map('length') is ansible.builtin.any"
    msg: "pve_group does not contain groups or groups with at least one host."

# make parallel deployment of multiple clusters possible
- name: Normalize pve_group list to host's group if in pve_group
  ansible.builtin.set_fact:
    pve_group: "{{ item.key }}"
  loop: "{{ groups | dict2items }}"
  when:
    - "pve_group is iterable"
    - "pve_group is not string"
    - "inventory_hostname in item.value"
    - "item.key in pve_group"

- name: Ensure that facts are present for all hosts
  ansible.builtin.assert:
    that: "hostvars[item].ansible_facts is defined"
    msg: "Could not load facts for {{ item }}. Run your playbook against all hosts in {{ pve_group }} with 'gather_facts: true'."
  loop: "{{ groups[pve_group] }}"
  when: "pve_cluster_enabled | bool"

- name: Ensure that hosts aren't in multiple groups at the same time
  ansible.builtin.assert:
    that: "inventory_hostname not in groups[item]"
    msg: "Host '{{ inventory_hostname }}' is declared in more than a single group ('{{ item }}' and '{{ pve_group }}')!
          make sure it only belongs to a single group (e.g. '{{ pve_group }}') in your inventory."
  loop: "{{ groups.keys() | list | difference(['all', pve_group]) }}"

# Mapping special variables
- name: Load corosync cluster variables
  block:
    - name: Ensure corosync_ring0_ip is normalized in the host facts
      ansible.builtin.set_fact:
        pve_cluster_addr0: "{{ corosync_ring0_ip | default(pve_cluster_addr0) | ansible.utils.ipaddr('address') }}"

    - name: Ensure pve_cluster_addr0 is a valid ip address
      ansible.builtin.assert:
        that: "pve_cluster_addr0 | default('', true) is ansible.utils.ip_address"
        msg: "The specified cluster ip address (pve_cluster_addr0={{ pve_cluster_addr0 }})
              of host {{ inventory_hostname }} is not a valid IP address in CIDR notation!"

    - name: Ensure corosync_ring1_ip is normalized in the host facts if defined
      ansible.builtin.set_fact:
        pve_cluster_addr1: "{{ corosync_ring1_ip | default(pve_cluster_addr1) | default('', true) | ansible.utils.ipaddr('address') }}"

    - name: Ensure pve_cluster_addr1 is a valid ip address if defined
      ansible.builtin.assert:
        that: "pve_cluster_addr1 is false or pve_cluster_addr1 is none or (pve_cluster_addr1 | default('', true) is ansible.utils.ip_address)"
        msg: "The specified cluster ip address (pve_cluster_addr1={{ pve_cluster_addr1 }})
              of host {{ inventory_hostname }} is defined but not a valid IP address in CIDR notation!"

# Mapping special variables
- name: Load Ceph network variables
  when: "pve_ceph_enabled | bool or pve_ceph_enhanced_enabled | bool"
  block:

    - name: Ensure pve_ceph_network is normalized in the host facts
      ansible.builtin.set_fact:
        pve_ceph_network: "{{ ceph_public_ip | default(pve_ceph_network) | ansible.utils.ipaddr('host/prefix') }}"

    - name: Ensure pve_ceph_network is a valid ip address
      ansible.builtin.assert:
        that: "pve_ceph_network | default('', true) | ansible.utils.ipaddr('address') is ansible.utils.ip_address"
        msg: "The specified Ceph network ip address (pve_ceph_network={{ pve_ceph_network }})
              of host {{ inventory_hostname }} is not a valid IP address in CIDR notation!"

    - name: Ensure pve_ceph_network network size is big enough
      ansible.builtin.assert:
        that: "pve_ceph_network | ansible.utils.ipaddr('size') >= 3"
        msg: "The specified Ceph network (pve_ceph_network={{ pve_ceph_network }}) size does not support 3 or more hosts!
              Ensure Ceph network variables have a correct netmask (<= 30) in their CIDR notation!"

    - name: Ensure pve_ceph_cluster_network is normalized in the host facts if defined
      ansible.builtin.set_fact:
        pve_ceph_cluster_network:
          "{{ ceph_cluster_ip | default(pve_ceph_cluster_network) | default('', true) | ansible.utils.ipaddr('host/prefix') }}"

    ## ansible.utils.ip_addess is only available in version < ansible-core 2.19  
    - name: Ensure pve_ceph_cluster_network is a valid ip address if defined 
      ansible.builtin.assert:
        that: "pve_ceph_cluster_network is false or pve_ceph_cluster_network is none or (pve_ceph_cluster_network | default('', true) is ansible.utils.ip_address )"
        msg: "The specified Ceph cluster network ip address (pve_ceph_cluster_network={{ pve_ceph_cluster_network }})
              of host {{ inventory_hostname }} is defined but not a valid IP address in CIDR notation!"
      when: (ansible_version.major >= 2) and (ansible_version.minor >= 19)

    - name: Ensure pve_ceph_cluster_network network size is big enough
      ansible.builtin.assert:
        that: "pve_ceph_cluster_network is false or pve_ceph_cluster_network is none 
              or (pve_ceph_cluster_network | ansible.utils.ipaddr('size') >= 3)"
        msg: "The specified Ceph cluster network (pve_ceph_cluster_network={{ pve_ceph_cluster_network }}) size does not support 3 or more hosts!
              Ensure Ceph network variables have a correct netmask (<= 30) in their CIDR notation!"

- name: Load Ceph MDS variables
  block:
    - name: Ensure no MDS are defined when no CephFS are defined
      ansible.builtin.set_fact:
        pve_ceph_mds_nodes: "{{ [] }}"
      when: "pve_ceph_fs is none or pve_ceph_fs | length == 0"

- name: Ensure pve_pin_kernel_version is a valid version string if defined
  ansible.builtin.assert:
    that:
      "pve_pin_kernel_version is false
      or pve_pin_kernel_version is none
      or pve_pin_kernel_version is regex('^(\\d{1,3}\\.){1,2}\\d{1,3}$')"
    msg: "The specified PVE kernel version (pve_pin_kernel_version={{ pve_pin_kernel_version }})
          is defined but not a valid PVE kernel version!"

# TODO: enable use of fqdn as inventory hostname
#- name: Ensure the inventory host and actual hostname are equal
#  ansible.builtin.assert:
#    that: "ansible_hostname == inventory_hostname"
#    msg: "Hostname declared in inventory: {{ inventory_hostname }} and actual hostname: {{ ansible_hostname }} must be equal!"

- name: Ensure that hosts group consists of more than one host to enable PVE clustering
  ansible.builtin.assert:
    that: "groups[pve_group] | length | int >= 2"
    msg: "Clustering is enabled for group {{ pve_group }} but does not meet the
          minimum requirement of at least 2 hosts. Please either remove/disable
          pve_cluster_enabled, or update your inventory to include at least 2 hosts."
  when: "pve_cluster_enabled | bool"

- name: Ensure either original or enhanced ceph task are selected
  ansible.builtin.assert:
    that: "not (pve_ceph_enabled | bool and pve_ceph_enhanced_enabled | bool)"
    msg: "Only either 'pve_ceph_enabled' or 'pve_ceph_enhanced_enabled' can be set to 'true'!"

- name: Ensure that group has at least 3 hosts if Ceph Clustering is enabled
  ansible.builtin.assert:
    that: "groups[pve_group] | length | int >= 3"
    msg: "Ceph configuration is enabled, but group {{ pve_group }} does not meet the requirement
          of at least 3 hosts. Please either remove/disable pve_ceph_enabled, pve_ceph_enhanced_enabled
          or update your inventory as to include at least 3 hosts in your group."
  when: "(pve_ceph_enabled | bool) or (pve_ceph_enhanced_enabled | bool)"

# TODO Make obsolete by adding cluster node destroy capability:
- name: Ensure this host is in the group specified
  ansible.builtin.fail:
    msg: "Host '{{ inventory_hostname }}' does not appear to be in its group {{ pve_group }},
          did you specify the pve_group variable correctly?"
  when: "(pve_cluster_enabled | bool) and (inventory_hostname not in groups[pve_group])"
