---
- name: Identify disks for Ceph-OSDs
  when: 
    - "pve_ceph_enhanced_enabled | bool"
    - "pve_ceph_osd_detection.enabled | default(false) | bool"
  block:
    - name: Fail if there are already a list of disks defined
      ansible.builtin.fail:
        msg: >-
          In the inventory there is already a list of OSD-disks defined
          in the variable 'pve_ceph_osds'. Either clear the list or set
          'pve_ceph_osd_detection.enabled' to false.
      when: pve_ceph_osds | length != 0

    - name: Gather all block devices
      ansible.builtin.setup:
        gather_subset:
          - hardware
          - all
      register: host_facts

    - name: Determine root device
      set_fact:
        root_device: >-
          {{
            host_facts.ansible_facts.ansible_mounts
            | selectattr('mount', 'equalto', '/')
            | map(attribute='device')
            | first
            | regex_replace('^/dev/', '')
            | regex_replace('p?[0-9]+$', '')
          }}

    - name: List non-root devices
      set_fact:
        nvme_disks: >-
          {{
            host_facts.ansible_facts.ansible_devices
            | dict2items
            | rejectattr('key', 'equalto', root_device)
            | selectattr('key', 'match', '^nvme')
            | map(attribute='key')
            | list
              if pve_ceph_osd_detection.only_nvme | default(false)
              else
            host_facts.ansible_facts.ansible_devices
            | dict2items
            | rejectattr('key', 'equalto', root_device)
            | selectattr('key', 'match', '^(vd|sd)')
            | map(attribute='key')
            | list
          }}

    - name: Fail if no suitable disks were found
      ansible.builtin.fail:
        msg: >-
          No eligible block devices were found on host {{ inventory_hostname }}.
          Check disk availability or your NVMe filtering settings.
      when: nvme_disks | length == 0

    - name: Build pve_ceph_osds structure
      set_fact:
        pve_ceph_osds: >-
          {{
            pve_ceph_osds | default([]) + [
              {
                'hosts': ansible_play_hosts_all,
                'device': '/dev/' + item,
                'encrypted': pve_ceph_osd_detection.encrypted | default(false)
              }
            ]
          }}
      loop: "{{ nvme_disks }}"
    
    # debug-output
    # - name: Show the pve_ceph_osds structure
    #   debug:
    #     var: pve_ceph_osds


# In case the used OSD came from an old Proxmox-VE / Ceph deployment, they must
# be wiped to make the usable as OSDs for the new ceph
# Requires that "pve_ceph_clear_all_osds" is set to true to enforce the cleanup
# It will be only done, when Ceph is not already installed, so only in case of a fresh installation.
- name: Cleanup old foreign Ceph-OSDs
  when: 
    - "pve_ceph_enhanced_enabled | default(false)"
    - "pve_ceph_clear_all_osds | default(false)"
  block:
    - name: Check if Ceph is installed
      command: ceph --version
      register: ceph_check
      changed_when: false
      failed_when: false

    - name: Set fact if Ceph is installed
      set_fact:
        ceph_installed: "{{ ceph_check.rc == 0 }}"

    - name: Warn if Ceph is already installed
      ansible.builtin.debug:
        msg: "WARNING: Ceph is already installed on this node. Skipping deletion of Ceph-OSDs, even it was requested via 'pve_ceph_clear_all_osds'."
      when: ceph_installed

    - name: Clear all declared Ceph OSD disks if requested
      ansible.builtin.shell: |
        dd if=/dev/zero of={{ item.device }} bs=1M count=100
        sync
      loop: "{{ pve_ceph_osds }}"
      when:
        - not ceph_installed
      register: _ceph_disk_clear
      changed_when: true
      failed_when: "_ceph_disk_clear.rc != 0"
        
# to stop the playbook here for debugging
# - name: Stop playbook execution here
#   ansible.builtin.meta: end_play
