---
- name: Check the ha migration strategy
  run_once: true
  block:

    - name: Check if /etc/pve/datacenter.cfg exists
      ansible.builtin.stat:
        path: "/etc/pve/datacenter.cfg"
      register: _pve_dc_cfg_exists

    - name: Fail if the HA migration strategy is not set to the default 'conditional'
      ansible.builtin.fail:
        msg: "No datacenter.cfg found, but the HA behavior is not set to the default of conditional "
      when:
        - not _pve_dc_cfg_exists.stat.exists
        - (pve_datacenter_options | default({})).ha | default("") == "conditional"

    - name: Slurp content of datacenter.cfg
      ansible.builtin.slurp:
        src: "/etc/pve/datacenter.cfg"
      register: _pve_dc_cfg_content
      when: _pve_dc_cfg_exists.stat.exists

    - name: Extract configured ha shutdown_policy
      ansible.builtin.set_fact:
        _pve_mig_strt: "{{ _pve_mig_strt_raw[0] | split('=') | json_query('[1]') }}"
      vars:
        _pve_mig_strt_raw: "{{ _pve_dc_cfg_content.content | b64decode | split('\n') |
                                select('match', 'ha: shutdown_policy') }}"
      when: _pve_dc_cfg_exists.stat.exists

    - name: Check if the HA migration strategy is configured according to /etc/pve/datacenter.cfg
      ansible.builtin.assert:
        that:
          - (pve_datacenter_options | default({})).ha | default("") == _pve_mig_strt
        fail_msg: "HA migration strategy is not configured according to /etc/pve/datacenter.cfg.
                  Adapt the configuration to proceed."
        success_msg: "HA migration strategy is configured according to /etc/pve/datacenter.cfg."
      when: _pve_dc_cfg_exists.stat.exists
