---
- name: Check the ha migration strategy
  run_once: true
  block:

    - name: Check if /etc/pve/datacenter.cfg exists
      ansible.builtin.stat:
        path: "/etc/pve/datacenter.cfg"
      register: _pve_dc_cfg_exists

    - name: Fail if the HA migration strategy is not set to the default 'conditional'
      ansible.builtin.fail:
        msg: "No datacenter.cfg found, but the HA behavior is not set to the default of conditional"
      when:
        - not _pve_dc_cfg_exists.stat.exists
        - (pve_datacenter_options | default({})).ha | default("") == "conditional"

    - name: Slurp content of datacenter.cfg
      ansible.builtin.slurp:
        src: "/etc/pve/datacenter.cfg"
      register: _pve_dc_cfg_content
      when: _pve_dc_cfg_exists.stat.exists

    - name: Extract configured HA shutdown policy
      ansible.builtin.set_fact:
        _pve_mig_strt: >-
          {{
            _pve_dc_cfg_content.content
            | regex_findall('(?m)^ha:\s*shutdown_policy=([^\s]+)')
            | first
            | default('')
          }}
      when: _pve_dc_cfg_exists.stat.exists

    - name: Check if the HA migration strategy is configured according to /etc/pve/datacenter.cfg
      ansible.builtin.assert:
        that:
          - (pve_datacenter_options | default({})).ha | default("") == _pve_mig_strt
          - _pve_mig_strt != ''
        fail_msg: "HA migration strategy (variable pve_datacenter_options) is not configured
                  according to /etc/pve/datacenter.cfg or is not configured at all.
                  Adapt the configuration to prevent unexpected changes in behavior."
        success_msg: "HA migration strategy is configured according to /etc/pve/datacenter.cfg."
      when: _pve_dc_cfg_exists.stat.exists
