---
- name: Verify Ceph version
  when: not pve_ceph_ignore_healthwarns
  block:
    - name: Retrieve Ceph version
      ansible.builtin.command:
        cmd: "ceph -v"
      register: _ceph_version_raw
      changed_when: false

    - name: Extract Ceph version string
      ansible.builtin.set_fact:
        _ceph_version: "{{ _ceph_version_list[4] }}"
      vars:
        _ceph_version_list: "{{ _ceph_version_raw.stdout | split(' ') }}"

    - name: Fail if Ceph version is not {{ pve_ceph_version }}
      ansible.builtin.fail:
        msg: "Ceph version must be {{ pve_ceph_version }}. Found: {{ _ceph_version }}"
      when: _ceph_version is not pve_ceph_version
