---
- name: Test for a healthy ceph cluster
  run_once: true
  when: (pve_ceph_enabled | bool) or (pve_ceph_enhanced_enabled | bool)
  block:
    - name: Get detailed Ceph health status
      ansible.builtin.command:
        cmd: "ceph health detail --format json"
      register: _ceph_health_detail_raw
      vars:
        _failed_filter: "{{ _ceph_health_detail_raw.stdout | from_json | json_query('status') }}"
      failed_when:
        - "_failed_filter != 'HEALTH_OK'"
        - not pve_ceph_ignore_healthwarns
      retries: "{{ pve_ceph_healthcheck_retries }}"
      delay: 10

  rescue:

    - name: Extract health details
      ansible.builtin.set_fact:
        _ceph_health_status: "{{ _ceph_health_detail['status'] }}"
        _ceph_health_checks: "{{ _ceph_health_detail['checks'] }}"
      vars:
        _ceph_health_detail: "{{ _ceph_health_detail_raw.stdout | from_json }}"

    - name: Gather current crash reports
      ansible.builtin.command:
        cmd: "ceph crash ls -f json"
      register: _ceph_crash_ls

    - name: Fail if health is not OK
      ansible.builtin.fail:
        msg: |
           ❌ Ceph summary status not OK: {{ _ceph_health_status | to_nice_yaml }}
           ❌ Contains check warnings for {{ _ceph_health_checks | to_nice_yaml }}
           ❌ Contains crash events -
           {{ _ceph_crash_ls.stdout | from_json | to_nice_yaml }}
