---

- name: Check if the active ceph manager service is available
  run_once: true
  ansible.builtin.command:
    cmd: "ceph mgr stat --format json"
  register: _ceph_status_raw
  changed_when: false
  until: "_ceph_status_raw.stdout | from_json | json_query('available')"
  retries: 5
